# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  IllusionEngine_config = debug
endif
ifeq ($(config),release)
  IllusionEngine_config = release
endif

PROJECTS := IllusionEngine

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

IllusionEngine:
ifneq (,$(IllusionEngine_config))
	@echo "==== Building IllusionEngine ($(IllusionEngine_config)) ===="
	@${MAKE} --no-print-directory -C . -f IllusionEngine.make config=$(IllusionEngine_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f IllusionEngine.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   IllusionEngine"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"